POST https://node-do-zero-aapj.onrender.com/videos
Content-type: application/json

{
    "title": "Video node",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

GET https://node-do-zero-aapj.onrender.com/videos

###

PUT https://node-do-zero-aapj.onrender.com/videos/d5022c13-811d-4e22-b06f-fb2b65aa7a43
Content-type: application/json

{
    "title": "Video Node 01",
    "description": "Primeiro video",
    "duration": 180
}

###

DELETE https://node-do-zero-aapj.onrender.com/videos/d5022c13-811d-4e22-b06f-fb2b65aa7a43