POST http://localhost:3333/videos
Content-type: application/json

{
    "title": "Video node",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/21b0cfe0-94f9-4cad-adf5-94008e48adea
Content-type: application/json

{
    "title": "Node.js",
    "description": "Primeiro video",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/21b0cfe0-94f9-4cad-adf5-94008e48adea